# Form implementation generated from reading ui file 'form_1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.choose_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.choose_btn.setGeometry(QtCore.QRect(80, 310, 201, 41))
        self.choose_btn.setObjectName("choose_btn")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 360, 111, 31))
        self.label.setObjectName("label")
        self.path_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.path_label.setGeometry(QtCore.QRect(80, 390, 661, 31))
        self.path_label.setText("")
        self.path_label.setObjectName("path_label")
        self.label_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(80, 170, 151, 31))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 200, 151, 31))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 230, 151, 31))
        self.label_5.setObjectName("label_5")
        self.max_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.max_label.setGeometry(QtCore.QRect(240, 170, 71, 21))
        self.max_label.setText("")
        self.max_label.setObjectName("max_label")
        self.avg_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.avg_label.setGeometry(QtCore.QRect(240, 200, 71, 21))
        self.avg_label.setText("")
        self.avg_label.setObjectName("avg_label")
        self.min_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.min_label.setGeometry(QtCore.QRect(240, 230, 71, 21))
        self.min_label.setText("")
        self.min_label.setObjectName("min_label")
        self.save_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(360, 310, 351, 41))
        self.save_btn.setObjectName("save_btn")
        self.save_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.save_label.setGeometry(QtCore.QRect(460, 280, 151, 16))
        self.save_label.setObjectName("save_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.choose_btn.setText(_translate("MainWindow", "Загрузить"))
        self.label.setText(_translate("MainWindow", "Выбранный файл:"))
        self.label_1.setText(_translate("MainWindow", "Максимальное значение:"))
        self.label_2.setText(_translate("MainWindow", "Среднее значение:"))
        self.label_5.setText(_translate("MainWindow", "Минимальное значение:"))
        self.save_btn.setText(_translate("MainWindow", "Сохранить"))
        self.save_label.setText(_translate("MainWindow", "Файл успешно сохранен!"))
