# Form implementation generated from reading ui file 'form_2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.open_btn.setGeometry(QtCore.QRect(540, 170, 91, 24))
        self.open_btn.setObjectName("open_btn")
        self.create_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_btn.setGeometry(QtCore.QRect(540, 140, 91, 24))
        self.create_btn.setObjectName("create_btn")
        self.save_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(540, 220, 101, 24))
        self.save_btn.setObjectName("save_btn")
        self.plain_panel = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plain_panel.setGeometry(QtCore.QRect(150, 140, 381, 381))
        self.plain_panel.setObjectName("plain_panel")
        self.path_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.path_label.setGeometry(QtCore.QRect(160, 100, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.path_label.setFont(font)
        self.path_label.setText("")
        self.path_label.setObjectName("path_label")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_btn.setText(_translate("MainWindow", "Открыть..."))
        self.create_btn.setText(_translate("MainWindow", "Создать..."))
        self.save_btn.setText(_translate("MainWindow", "Сохранить"))
        self.label.setText(_translate("MainWindow", "Файл:"))
