# Form implementation generated from reading ui file 'form_4.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(706, 537)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_image = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(160, 90, 341, 301))
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.slider_alpha = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider_alpha.setGeometry(QtCore.QRect(160, 420, 341, 31))
        self.slider_alpha.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_alpha.setObjectName("slider_alpha")
        self.btn_open = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_open.setGeometry(QtCore.QRect(540, 100, 91, 31))
        self.btn_open.setObjectName("btn_open")
        self.btn_reset = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_reset.setGeometry(QtCore.QRect(540, 140, 91, 31))
        self.btn_reset.setObjectName("btn_reset")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_open.setText(_translate("MainWindow", "Открыть..."))
        self.btn_reset.setText(_translate("MainWindow", "Сброс"))
