# Form implementation generated from reading ui file 'form_5.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_flag = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_flag.setGeometry(QtCore.QRect(120, 120, 400, 300))
        self.label_flag.setText("")
        self.label_flag.setObjectName("label_flag")
        self.btn_generate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_generate.setGeometry(QtCore.QRect(570, 220, 131, 51))
        self.btn_generate.setObjectName("btn_generate")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_generate.setText(_translate("MainWindow", "Сгенерировать флаг"))
