# Form implementation generated from reading ui file 'form_3.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 553)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_image = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(150, 80, 381, 321))
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.btn_open = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_open.setGeometry(QtCore.QRect(590, 70, 131, 31))
        self.btn_open.setObjectName("btn_open")
        self.btn_rotate_left = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_rotate_left.setGeometry(QtCore.QRect(590, 120, 131, 21))
        self.btn_rotate_left.setObjectName("btn_rotate_left")
        self.btn_rotate_right = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_rotate_right.setGeometry(QtCore.QRect(590, 160, 131, 24))
        self.btn_rotate_right.setObjectName("btn_rotate_right")
        self.btn_remove_red = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_remove_red.setGeometry(QtCore.QRect(590, 200, 131, 21))
        self.btn_remove_red.setObjectName("btn_remove_red")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_open.setText(_translate("MainWindow", "Открыть картинку..."))
        self.btn_rotate_left.setText(_translate("MainWindow", "Повернуть налево"))
        self.btn_rotate_right.setText(_translate("MainWindow", "Повернуть направо"))
        self.btn_remove_red.setText(_translate("MainWindow", "Удалить красный слой"))
