# Form implementation generated from reading ui file 'form_7.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 482)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_c = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_c.setGeometry(QtCore.QRect(120, 110, 51, 221))
        self.btn_c.setObjectName("btn_c")
        self.btn_d = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_d.setGeometry(QtCore.QRect(180, 110, 51, 221))
        self.btn_d.setObjectName("btn_d")
        self.btn_e = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_e.setGeometry(QtCore.QRect(240, 110, 51, 221))
        self.btn_e.setObjectName("btn_e")
        self.btn_f = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_f.setGeometry(QtCore.QRect(300, 110, 51, 221))
        self.btn_f.setObjectName("btn_f")
        self.btn_g = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_g.setGeometry(QtCore.QRect(360, 110, 51, 221))
        self.btn_g.setObjectName("btn_g")
        self.btn_a = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_a.setGeometry(QtCore.QRect(420, 110, 51, 221))
        self.btn_a.setObjectName("btn_a")
        self.btn_b = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_b.setGeometry(QtCore.QRect(480, 110, 51, 221))
        self.btn_b.setObjectName("btn_b")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_c.setText(_translate("MainWindow", "do"))
        self.btn_d.setText(_translate("MainWindow", "re"))
        self.btn_e.setText(_translate("MainWindow", "mi"))
        self.btn_f.setText(_translate("MainWindow", "fa"))
        self.btn_g.setText(_translate("MainWindow", "sol"))
        self.btn_a.setText(_translate("MainWindow", "la"))
        self.btn_b.setText(_translate("MainWindow", "ci"))
