# Form implementation generated from reading ui file 'form_6.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_smiley = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_smiley.setGeometry(QtCore.QRect(180, 120, 411, 341))
        self.label_smiley.setText("")
        self.label_smiley.setObjectName("label_smiley")
        self.btn_color = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_color.setGeometry(QtCore.QRect(630, 120, 111, 31))
        self.btn_color.setObjectName("btn_color")
        self.slider_scale = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider_scale.setGeometry(QtCore.QRect(640, 170, 101, 351))
        self.slider_scale.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.slider_scale.setObjectName("slider_scale")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_color.setText(_translate("MainWindow", "Выбрать цвет"))
