# Form implementation generated from reading ui file 'form_8.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(996, 733)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_generate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_generate.setGeometry(QtCore.QRect(850, 127, 111, 31))
        self.btn_generate.setObjectName("btn_generate")
        self.btn_open = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_open.setGeometry(QtCore.QRect(850, 90, 111, 31))
        self.btn_open.setObjectName("btn_open")
        self.slider_iterations = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider_iterations.setGeometry(QtCore.QRect(790, 690, 191, 31))
        self.slider_iterations.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_iterations.setObjectName("slider_iterations")
        self.slider_scale = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider_scale.setGeometry(QtCore.QRect(20, 90, 16, 601))
        self.slider_scale.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.slider_scale.setObjectName("slider_scale")
        self.label_status = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(830, 650, 151, 21))
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.label_canvas = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_canvas.setGeometry(QtCore.QRect(40, 80, 800, 600))
        self.label_canvas.setText("")
        self.label_canvas.setObjectName("label_canvas")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_generate.setText(_translate("MainWindow", "Generate"))
        self.btn_open.setText(_translate("MainWindow", "Open"))
